### ISSUE TITLE
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)'

### ISSUE THREAD

**Issue by kematy** [rust-embedded-community/serde-json-core#33] opened 2020-06-22 05:45 UTC
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', src\lib.rs:124:23

line 124:
let json_obj: Value=serde_json::from_str(s.as_str()).unwrap();

**Comment by MathiasKoch** [comment] 2020-10-09 05:30
@kematy That is intended behaviour?

There are a number of issues here, most important one being that you are using `serde_json`, rather than `serde_json_core` (different crate, https://github.com/serde-rs/json)

You are calling `unwrap()` on an error type, causing a panic.

The reason it returns an error, seems to be that you are attempting to parse invalid JSON, though this is just a guess without knowing the contents of `s.as_str()`

**Comment by MathiasKoch** [comment] 2020-12-11 07:16
Closing this with reference to above comment about it being a user error.

Feel free to re-open if this is still an issue.

**Closed by MathiasKoch** 2020-12-11 07:16 UTC
